data:
  ETTh1:
    data_path: f"https://raw.githubusercontent.com/zhouhaoyi/ETDataset/main/ETT-small/ETTh1.csv"
  ETTm1:
    data_path: f"https://raw.githubusercontent.com/zhouhaoyi/ETDataset/main/ETT-small/ETTm1.csv"
  # Traffic:
model_type: "vanilla"
model:
  context_length: 512
  num_input_channels: 7
  patch_length: 12
  forecast_horizon: 96
  d_model: 128
  num_attention_heads: 16
  num_hidden_layers: 3
training:
  dataset: "ETTh1"
  num_workers: 2
  epochs: 100
  batch_size: 32
  learning_rate: 0.001
logging:
  wandb_project: "patchtst-flashattention"
  wandb_entity: "patchtst-flashattention"
  wandb_run_name: "project-test"