data:
  ETTh1:
    data_path: f"https://raw.githubusercontent.com/zhouhaoyi/ETDataset/main/ETT-small/ETTh1.csv"
  ETTm1:
    data_path: f"https://raw.githubusercontent.com/zhouhaoyi/ETDataset/main/ETT-small/ETTm1.csv"
  # Traffic:
model:
  context_length: 512
  forecast_horizon: 96
  patch_length: 12
training:
  dataset: "ETTh1"
  num_workers: 2
  epochs: 100
  batch_size: 32
  learning_rate: 0.001
logging:
  wandb_project: "patchtst-flashattention"
  wandb_entity: "patchtst-flashattention"
  wandb_run_name: "project-test"

